sealed-secrets:
  fullnameOverride: aissemble-sealed-secrets-controller

  # Update sealed secrets image to use bitnami legacy registry
  image:
    repository: bitnamilegacy/sealed-secrets-controller

  annotations:
    category: DeveloperTools
    images: |
      - name: sealed-secrets-controller
        image: docker.io/bitnamilegacy/sealed-secrets-controller:0.26.2-debian-12-r0