[#_messaging_details]
= Messaging

== Overview
Messaging is used to provide a decoupled orchestration of events and data between pipeline steps and between the
pipeline and external systems.  By leveraging messaging, the pipeline model can be used to define the flow of data
through the pipeline, instead of manually controlling the flow via the pipeline driver.  Pipeline messaging utilizes
an implementation of the Reactive Messaging Specification by Eclipse. (See <<Advanced-Details>> section for more info.)

=== Basic Concepts
The following messaging concepts are useful in understanding this document.
[cols="1,5"]
|===
| *Publisher*
| A unit of code that produces messages upon request. Sometimes called a source.
| *Subscriber*
| A unit of code that consumes messages. Sometimes called a sink.
| *Processor*
| A unit of code that is simultaneously a Publisher and Subscriber. It consumes an incoming message and uses the
data to produce an outgoing message.
| *Channel*
| The means by which messages flow. All sources and processors push created messages onto channels, and all sinks
and processors pull messages from channels.
|===

In aiSSEMBLE, a channel is backed by the message broker service in the form of a queue or topic.  The source and
sinks of a pipeline can reside within the pipeline itself or external sources via the message broker service.

image::pipeline-messaging-basic.svg[Messaging architecture]

//todo our What Gets Generated sections are mildly inconsistent. Worth unifying
== What Gets Generated
=== _microprofile-config.properties_
This is the standard configuration file per the reactive messaging specification.  Any reactive messaging
configuration that does not pertain to pipeline messaging should be placed here.

=== _org.eclipse.microprofile.config.spi.ConfigSource_
This file specifies other custom reactive messaging configuration sources. By default, two custom sources are
created and registered in this file

 com.boozallen.aiops.data.delivery.messaging.PipelineMessagingConfig

The `PipelineMessagingConfig` source exposes fine-grained reactive messaging configuration that backs pipeline
messaging for advanced use cases. See the <<Customization>> section for more details.

 <pipeline-package-and-name>DefaultConfig

The pipeline default configuration provides sensible defaults to support messaging within the pipeline. These
defaults can be overridden by utilizing the `PipelineMessagingConfig` mentioned above.

[#Customization]
== Customization
[#Advanced-Details]
=== Advanced Details
Pipeline messaging leverages the https://smallrye.io/smallrye-reactive-messaging[Smallrye implementation,role=external,window=_blank]
of the https://download.eclipse.org/microprofile/microprofile-reactive-messaging-1.0/microprofile-reactive-messaging-spec.html[Reactive
Messaging specification,role=external,window=_blank]. In order to fully understand how to customize messaging and what
can be customized, it's important to understand how reactive messaging is leveraged to achieve pipeline messaging.

For the most part, the concepts of pipeline messaging parallel the concepts of reactive messaging.  The primary
difference is how channels operate.  As discussed in <<Basic Concepts>>, a pipeline channel is backed by a message
broker service and flows all messages through the message broker.  In contrast, a reactive messaging channel is
completely internal to the process that is using reactive messaging (e.g. the pipeline).  In order to connect to
external systems, reactive messaging uses *Connectors* to attach a topic or queue in a message broker to either the
incoming or outgoing side of a channel.  Therefore, a pipeline channel is better represented by the following model:

image::pipeline-messaging-channel.svg[Pipeline channel]

Using this expanded representation, we can redraw the previous pipeline messaging diagram as the following:

image::pipeline-messaging-adv.svg[Messaging implementation]

=== Configuration
aiSSEMBLE provides for advanced customization of the reactive channels and connectors that back pipeline messaging
via the `pipeline-messaging.properties` krausening file.

All configuration properties outlined by the
https://download.eclipse.org/microprofile/microprofile-reactive-messaging-1.0/microprofile-reactive-messaging-spec.html#_configuration[Reactive
Messaging specification,role=external,window=_blank] and the
https://smallrye.io/smallrye-reactive-messaging/latest/concepts/connectors/#configuring-connectors[Smallrye
documentation,role=external,window=_blank] is available but must be translated to reference a pipeline step instead
of directly referencing a reactive channel by name.  Instead of
`mp.messaging.[incoming|outgoing].[channel-name].[attribute]=[value]`, the configuration pattern becomes
`[step-name].[in|out].[attribute]=[value,role=external,window=_blank]`

Consider the following example configuration from the smallrye documentation:

[source,properties]
----
mp.messaging.incoming.health.topic=neo
mp.messaging.incoming.health.connector=smallrye-mqtt
mp.messaging.incoming.health.host=localhost

mp.messaging.outgoing.data.connector=smallrye-kafka
mp.messaging.outgoing.data.bootstrap.servers=localhost:9092
mp.messaging.outgoing.data.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.data.value.serializer=io.vertx.kafka.client.serialization.JsonObjectSerializer
mp.messaging.outgoing.data.acks=1
----

If this configuration were translated to a pipeline-messaging.properties configuration for a step named IngestData,
it would become the following:

[source,properties]
----
IngestData.in.topic=neo
IngestData.in.connector=smallrye-mqtt
IngestData.in.host=localhost

IngestData.out.connector=smallrye-kafka
IngestData.out.bootstrap.servers=localhost:9092
IngestData.out.key.serializer=org.apache.kafka.common.serialization.StringSerializer
IngestData.out.value.serializer=io.vertx.kafka.client.serialization.JsonObjectSerializer
IngestData.out.acks=1
----