{{- if not .Values.s3LocalEnabled -}}
# Convert this to a SealedSecret using kubeseal and replace it here
apiVersion: v1
kind: Secret
metadata:
  namespace: ${parentArtifactId}
  name: remote-auth-config
stringData:
  YOUR_SECRET_KEY: YOUR_SECRET_VALUE
  YOUR_SECRET_KEY: YOUR_SECRET_VALUE
{{- end -}}