# Convert this to a SealedSecret using kubeseal and replace it here

apiVersion: v1
kind: Secret
metadata:
  namespace: argocd
  name: remote-auth-config
stringData:
  YOUR_SECRET_KEY: YOUR_SECRET_VALUE
  YOUR_SECRET_KEY: YOUR_SECRET_VALUE
