---
app:
  # Sets labels for app.kubernetes.io/name Default is Chart.Name (Quarkus)
  name: ''
  # Sets the labels for app.kubernetes.io/version. Default is Chart.AppVersion
  version: ''
deployment:
  image:
    repo: ghcr.io/
    # Override with specific image
    name: boozallen/aissemble-quarkus
    # Overrides the default chart AppVersion value
    tag: ''
    # Default IfNotPresent
    imagePullPolicy: ''
  volumeMounts:
    - name: quarkus-application-properties
      mountPath: /deployments/config/application.properties
      subPath: quarkus-properties-file
  volumes:
    - name: quarkus-application-properties
      configMap:
        name: supplemental-quarkus-config
        items:
          - key: quarkus-properties-file
            path: quarkus-properties-file
  securityContext: {}
  # Defaults to the default user in cluster
  serviceAccountName: ''
  automountServiceAccountToken: false
  env: []
  args: []
  # Defaults to Chart.Name
  hostname: ''
  restartPolicy: Always

service:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080

configMap:
  name: supplemental-quarkus-config
  supplementalQuarkusConfig: []

ingress:
  enabled: false
  metadata:
    annotations:
  hosts:
    - host:
      paths:
