<?xml version="1.0" encoding="UTF-8"?>
<!--
  #%L
  aiSSEMBLE::Foundation::Upgrade
  %%
  Copyright (C) 2021 Booz Allen
  %%
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  #L%
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.test</groupId>
        <artifactId>test-data-encryption-pipelines</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>simple-pipeline</artifactId>
    <packaging>jar</packaging>

    <name>Test Data Encryption Removal::Pipelines::Simple Pipeline</name>
    <description>${pipeline.description}</description>

    <build>
        <plugins>
            <plugin>
                <groupId>org.technologybrewery.fermenter</groupId>
                <artifactId>fermenter-mda</artifactId>
                <configuration>
                    <basePackage>org.test</basePackage>
                    <profile>data-delivery-spark-pipeline</profile>
                    <propertyVariables>
                        <targetPipeline>SimplePipeline</targetPipeline>
                        <aissembleVersion>${version.aissemble}</aissembleVersion>
                        <dockerProjectRepositoryUrl>${docker.project.repository.url}</dockerProjectRepositoryUrl>
                    </propertyVariables>
                    <!-- see test-data-encryption-pipelines for base configuration settings -->
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.googlecode.maven-java-formatter-plugin</groupId>
                <artifactId>maven-java-formatter-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <!-- NOTE: These are the minimum required transformers needed to run a basic
                                data-delivery-spark pipeline within the Spark container. Please be aware that
                                it is tricky to debug issues related to the transformer configuration, and
                                you may need to add additional transformers depending on your implementation. -->
                                <transformer
                                    implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>org.test.SimplePipelineDriver</mainClass>
                                </transformer>
                                <transformer
                                    implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/services/</resource>
                                </transformer>
                                <transformer
                                    implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/services/org.apache.spark.sql.sources.DataSourceRegister</resource>
                                </transformer>
                                <transformer
                                    implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <!-- It seems the shaded jar only has javax.* providers at the moment. Re-evaluate after JDK 17 upgrade is complete. -->
                                    <resource>META-INF/services/javax.ws.rs.ext.Providers</resource>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>main-chart</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>helm</executable>
                            <arguments>
                                <argument>template</argument>
                                <argument>${aissemble.helm.repo.protocol}://${aissemble.helm.repo}/aissemble-spark-application-chart</argument>
                                <argument>--version</argument>
                                <argument>${version.aissemble}</argument>
                                <argument>--values</argument>
                                <argument>src/main/resources/apps/simple-pipeline-base-values.yaml,src/main/resources/apps/simple-pipeline-dev-values.yaml</argument>
                                <argument>-s</argument>
                                <argument>templates/deployment.yaml</argument>
                            </arguments>
                            <outputFile>target/apps/simple-pipeline-dev-chart.yaml</outputFile>
                        </configuration>
                    </execution>
                    <execution>
                        <id>test-chart</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>helm</executable>
                            <arguments>
                                <argument>template</argument>
                                <argument>${aissemble.helm.repo.protocol}://${aissemble.helm.repo}/aissemble-spark-application-chart</argument>
                                <argument>--version</argument>
                                <argument>${version.aissemble}</argument>
                                <argument>--values</argument>
                                <argument>src/main/resources/apps/simple-pipeline-base-values.yaml,src/test/resources/apps/simple-pipeline-test-values.yaml</argument>
                                <argument>-s</argument>
                                <argument>templates/deployment.yaml</argument>
                            </arguments>
                            <outputFile>target/apps/simple-pipeline-test-chart.yaml</outputFile>
                        </configuration>
                    </execution>
                    <execution>
                        <id>ci-chart</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>helm</executable>
                            <arguments>
                                <argument>template</argument>
                                <argument>${aissemble.helm.repo.protocol}://${aissemble.helm.repo}/aissemble-spark-application-chart</argument>
                                <argument>--version</argument>
                                <argument>${version.aissemble}</argument>
                                <argument>--values</argument>
                                <argument>src/main/resources/apps/simple-pipeline-base-values.yaml,src/main/resources/apps/simple-pipeline-ci-values.yaml</argument>
                                <argument>-s</argument>
                                <argument>templates/deployment.yaml</argument>
                            </arguments>
                            <outputFile>target/apps/simple-pipeline-ci-chart.yaml</outputFile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>net.masterthought</groupId>
                <artifactId>maven-cucumber-reporting</artifactId>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.technologybrewery.krausening</groupId>
            <artifactId>krausening</artifactId>
        </dependency>
        <dependency>
            <groupId>com.boozallen.aissemble</groupId>
            <artifactId>foundation-core-java</artifactId>
        </dependency>
        <dependency>
            <groupId>com.boozallen.aissemble</groupId>
            <artifactId>foundation-metadata-producer</artifactId>
        </dependency>
        <dependency>
            <groupId>com.boozallen.aissemble</groupId>
            <artifactId>extensions-messaging-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>com.boozallen.aissemble</groupId>
            <artifactId>extensions-data-delivery-spark</artifactId>
        </dependency>
        <dependency>
            <groupId>com.boozallen.aissemble</groupId>
            <artifactId>extensions-data-delivery-spark</artifactId>
            <classifier>tests</classifier>
            <type>test-jar</type>
            <scope>test</scope>
            <version>${version.aissemble}</version>
        </dependency>
        <dependency>
            <!-- Spark hasn't migrated to Jakarta packages yet. Will need to shade it if we want to fully migrate. -->
            <!-- See https://github.com/apache/incubator-hugegraph-toolchain/issues/464 -->
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>${version.javax.servlet}</version>
        </dependency>
        <dependency>
            <groupId>com.boozallen.aissemble</groupId>
            <artifactId>foundation-pdp-client-java</artifactId>
        </dependency>
        <dependency>
            <groupId>com.boozallen.aissemble</groupId>
            <artifactId>extensions-authzforce</artifactId>
        </dependency>
        <dependency>
            <groupId>io.smallrye.reactive</groupId>
            <artifactId>smallrye-reactive-messaging-kafka</artifactId>
            <version>${version.smallrye.reactive.messaging}</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>test-data-encryption-data-records-java</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!-- Test dependencies: -->
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.smallrye.reactive</groupId>
            <artifactId>smallrye-reactive-messaging-in-memory</artifactId>
            <version>${version.smallrye.reactive.messaging}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.awaitility</groupId>
            <artifactId>awaitility</artifactId>
            <version>${version.awaitility}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.masterthought</groupId>
            <artifactId>cucumber-reporting</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
