allow_k8s_contexts('local')
docker_prune_settings(num_builds=1, keep_recent=1)

aissemble_version = '${archetypeVersion}'

build_args = { 'DOCKER_BASELINE_REPO_ID': 'ghcr.io/',
               'VERSION_AISSEMBLE': aissemble_version}

load('ext://namespace', 'namespace_create')
namespace_create('${artifactId}')

# Kafka
yaml = helm(
    '${artifactId}-deploy/src/main/resources/apps/kafka-cluster',
    values=['${artifactId}-deploy/src/main/resources/apps/kafka-cluster/values.yaml',
        '${artifactId}-deploy/src/main/resources/apps/kafka-cluster/values-dev.yaml']
)
k8s_yaml(yaml)

# Add deployment resources here