<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.boozallen.aissemble</groupId>
        <artifactId>extensions-docker</artifactId>
        <version>1.12.0</version>
    </parent>

    <artifactId>aissemble-hive-service</artifactId>
    <name>aiSSEMBLE::Extensions::Docker::Hive Service</name>
    <description>A base image for a Hive Metastore Service</description>

    <packaging>docker-build</packaging>

    <properties>
        <dockerbuild.jars.directory>target/dockerbuild/lib</dockerbuild.jars.directory>
        <dockerbuild.bin.directory>target/dockerbuild/bin</dockerbuild.bin.directory>
        <dockerbuild.patch.directory>target/dockerbuild/patch</dockerbuild.patch.directory>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.delta</groupId>
            <artifactId>delta-hive_2.12</artifactId>
            <version>3.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.hive</groupId>
            <artifactId>hive-standalone-metastore-server</artifactId>
            <version>${version.hive}</version>
            <classifier>bin</classifier>
            <type>tar.gz</type>
            <exclusions>
                <exclusion>
                    <groupId>jdk.tools</groupId>
                    <artifactId>jdk.tools</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- Patch JARs -->
        <dependency>
            <groupId>io.airlift</groupId>
            <artifactId>aircompressor</artifactId>
            <version>0.27</version>
        </dependency>
        <dependency>
            <groupId>org.apache.avro</groupId>
            <artifactId>avro</artifactId>
            <version>1.11.4</version>
        </dependency>
        <dependency>
            <groupId>dnsjava</groupId>
            <artifactId>dnsjava</artifactId>
            <version>3.6.2</version>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-protobuf</artifactId>
            <version>1.70.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>33.4.0-jre</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.18.2</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-io</artifactId>
            <version>9.4.57.v20241219</version>
        </dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>8.2.0</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-codec-http2</artifactId>
            <version>4.1.117.Final</version>
        </dependency>
        <dependency>
            <groupId>com.nimbusds</groupId>
            <artifactId>nimbus-jose-jwt</artifactId>
            <version>9.48</version>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.5.5</version>
        </dependency>
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>3.25.5</version>
        </dependency>
        <dependency>
            <groupId>org.xerial.snappy</groupId>
            <artifactId>snappy-java</artifactId>
            <version>1.1.10.7</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
            <version>5.3.26</version>
        </dependency>
        <dependency>
            <groupId>org.apache.zookeeper</groupId>
            <artifactId>zookeeper</artifactId>
            <version>3.9.3</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>${group.fabric8.plugin}</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <configuration>
                    <images>
                        <image>
                            <build>
                                <args>
                                    <METASTORE_VERSION>${version.hive}</METASTORE_VERSION>
                                    <JARS_DIR>${dockerbuild.jars.directory}</JARS_DIR>
                                    <BIN_DIR>${dockerbuild.bin.directory}</BIN_DIR>
                                    <PATCH_DIR>${dockerbuild.patch.directory}</PATCH_DIR>
                                </args>
                            </build>
                        </image>
                    </images>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <configuration>
                    <excludeTransitive>true</excludeTransitive>
                </configuration>
                <executions>
                    <execution>
                        <id>get-extra-libs</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${dockerbuild.jars.directory}</outputDirectory>
                            <includeTypes>jar</includeTypes>
                            <includeArtifactIds>delta-hive_2.12</includeArtifactIds>
                        </configuration>
                    </execution>
                    <execution>
                        <id>get-patch-jars</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${dockerbuild.patch.directory}</outputDirectory>
                            <includeTypes>jar</includeTypes>
                            <excludeArtifactIds>delta-hive_2.12,fermenter-mda,baton-maven-plugin,habushu-maven-plugin</excludeArtifactIds>
                            <useRepositoryLayout>true</useRepositoryLayout>
                        </configuration>
                    </execution>
                    <execution>
                        <id>get-metastore</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${dockerbuild.bin.directory}</outputDirectory>
                            <includeArtifactIds>hive-standalone-metastore-server</includeArtifactIds>
                            <stripVersion>true</stripVersion>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>wagon-maven-plugin</artifactId>
                <version>2.0.2</version>
                <executions>
                    <execution>
                        <id>get-hadoop</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>download-single</goal>
                        </goals>
                        <configuration>
                            <url>https://dlcdn.apache.org</url>
                            <fromFile>hadoop/common/hadoop-${version.hadoop}/hadoop-${version.hadoop}.tar.gz</fromFile>
                            <toFile>${dockerbuild.bin.directory}/hadoop.tar.gz</toFile>
                            <skipIfExists>true</skipIfExists>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>integration-test</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>${group.fabric8.plugin}</groupId>
                        <artifactId>docker-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>test-image</id>
                                <phase>integration-test</phase>
                                <configuration>
                                    <images>
                                        <image>
                                            <run>
                                                <network>
                                                    <!-- bridged mode (the default) does not work reliably for direct tcp verification.
                                                    See https://github.com/fabric8io/docker-maven-plugin/issues/1234#issuecomment-2609924715 -->
                                                    <mode>host</mode>
                                                </network>
                                                <wait>
                                                    <tcp>
                                                        <ports>
                                                            <port>9083</port>
                                                        </ports>
                                                    </tcp>
                                                </wait>
                                            </run>
                                        </image>
                                    </images>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>test-image-cleanup</id>
                                <phase>post-integration-test</phase>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
