apiVersion: v2
name: aissemble-policy-decision-point-chart
description: A Helm chart for policy-decision-point
# Version is automatically set by the plugin so this is only a placeholder
version: 1.0.0
# App Version is automatically set by the plugin so this is only a placeholder
appVersion: 1.0.0
sources:
  - https://github.com/boozallen/aissemble