= Leveraging the Configuration Store

== Overview
The Configuration Store is a tool that enables the various configurations for a project to be centrally defined and
managed, while also standardizing access to the configurations. The Configuration Store dynamically provides
environment-specific configurations, based on the project's development lifecycle phase by leverages the opensource
project https://github.com/TechnologyBrewery/krausening[Krausening]. Usage limitations and regeneration strategies can
also be set, allowing configurations to automatically refreshed, thereby bolstering security of sensitive properties.

=== Setup
The Configuration Store tool is currently under development. Stay tuned for its release!

=== Usage
Via the configuration store's helm chart, project teams can specify environment variables with the URIs that house
the project's various Krausening properties. It is required to
specify a base property URI that houses the base/default
property configurations. Optionally, one can specify a base policy URI that houses the base/default policy configurations.

In addition to the base URIs, one can optionally specify a secondary URI for both properties and/or policies that
houses environment-specific configurations that will override and/or augment the respective base configurations.
Multiple configuration files can be stored at any given URI. Further guidance is covered below.

Since it is common practice to define separate Helm chart values for each environment of a project's development 
lifecycle, it is encouraged to define one shared base URI and respective environment-specific URIs, each housing
the relevant overrides and augmentations.

The following example Configuration Store Helm chart demonstrates a URI specifications for a CI deployment:
[source,yaml]
----
  env:
    KRAUSENING_BASE: <URI housing base property configurations>
    KRAUSENING_EXTENSIONS: <URI housing CI-specific property overrides/augmentations>
    BASE_POLICY_URI: <URI housing base property regeneration policies>
    ENVIRONMENT_POLICY_URI: <URI housing CI-specific property regeneration policies>
----

==== Properties
Properties represent key values pairs for storing your project configurations. The key values pairs are stored as 
string types using the standard `.properties` file format.

Suppose we defined the following property configurations file named `messaging.properties` at the `KRAUSENING_BASE`:
[source,properties]
----
connector=smallrye-kafka
topic=baseTopic
----

Next, suppose we defined the following property configurations file named `messaging.properties` at the
`KRAUSENING_EXTENSIONS`:
[source,properties]
----
topic=ciTopic
auth-token=auth-secret
----

When these two configuration file are reconciled within the Configuration Store, it results in a configuration with
a group name of `messaging` equivalent to the following:
[source,properties]
----
connector=smallrye-kafka
topic=ciTopic
auth-token=auth-secret
----

Such that the following calls to the tool would provide the following configurations:
[source,java]
----
ConfigServiceClient client = new ConfigServiceClient();
client.getProperty("messaging", "connector")   ---> smallrye-kafka
client.getProperty("messaging", "topic")       ---> ciTopic
client.getProperty("messaging", "auth-token")  ---> auth-secret
----

For more information on property definition and usage, visit
https://github.com/TechnologyBrewery/krausening[Krausening].

==== Properties Storage Options
The universal config store offers robust production ready configuration storage using vault. This is an excellent
solution for large enterprise applications. For smaller applications looking for a more light weight but still robust
storage option, the universal config can be set to use Krausening. The universal config can also be set up to use in
memory storage if you need to run some quick local tests.

The default property storage is Krausening. To change it to use one of the other options you can set the environment
variable STORAGE_CLASS. The values currently available are `krausening`, `vault`, and `inMemory`

==== Property Regeneration Policies
Policies are used to define limitations and rules for when a given property should be regenerated. This allows the user
to outline which properties they would like to be regenerated, when they would like them to be regenerated, and how to 
regenerate them. The policies are defined in `JSON` format using the options below.


.Property Regeneration Policy Options
[cols="2,1,5"]
|===
| Element Name | Required | Use

| `identifier`
| Yes
| Unique name for the policy. A policy with the same identifier in the environment specific policies will override the its respective
 base policy.

| `description`
| No
| A statement of what the policy is for.

| `targets`
| Yes
| List of properties that the policy applies to. Can be one to many targets for a given policy. Multiple policies cannot share the same
 target property (exception for targets being shared between an environment policy and its respective base policy).

| `targets/retrieve_url`
| Yes
| Describes where the property lives in the format `/GROUP_NAME/PROPERTY_NAME`.

| `rules`
| Yes
| Logic to be executed when any of the properties within `targets` are accessed. The rule will determine whether the target property(ies)
 need to be regenerated or can continued being used. Can be one to many rules for a given policy.

| `rules/className`
| Yes
| Java class that contains the necessary implementation for executing the rule.

| `rules/configurations`
| No
| Additional configuration details to pass to rule implementation. Can be zero to many key value pairs for a given rule.

| `regeneration_method`
| Yes
| Logic to be executed when any of the `rules` determine that the target property(ies) need to be regenerated. The regeneration method can provide
 updated values for zero to all of the properties specified in `targets`, however it cannot update properties not explicitly specified in `targets`.
 There is only one regeneration method for a given policy.

| `regeneration_method/className`
| Yes
| Java class that contains the necessary implementation for executing the regeneration method.

| `regeneration_method/configurations`
| No
| Additional configuration details to pass to regeneration method implementation. Can be zero to many key value pairs for a given
 regeneration method.

|===

Basic example of a policy configuration:
[source,json]
----
[
  {
    "identifier": "messaging-auth-token-policy",
    "description": "Policy for updating the messaging auth token when its 5 days old",
    "targets": [
      {
        "retrieve_url": "/messaging/auth-token"
      }
    ],
    "rules": [
      {
        "className": "your.custom.Limitation",
        "configurations":{
            "expirationDate": "5 Days"
        }
      }
    ],
    "regeneration_method": {
      "className": "your.custom.AuthTokenRefresh",
      "configurations":{
          "endpoint": "https://your-new-token-service.org/getNewToken?exp=5days"
      }
    }
  }
]
----
This policy is defining a rule and regeneration method for a targeted property with the group name `messaging` and property
name `auth-token`. When the property is accessed, the `Limitation` rule will be run to see if the property needs to be 
regenerated. In the event that it does, then the `AuthTokenRefresh` regeneration method will be run and the respective value
will be updated in the Configuration Store.

More complex example of a policy configuration:
[source,json]
----
[
  {
    "identifier":"aws-credentials-policy",
    "description": "Policy for updating AWS creds when there old or accessed too many times",
    "targets": [
      {
        "retrieve_url":"/aws-access/AWS_ACCESS_KEY_ID"
      },
      {
        "retrieve_url":"/aws-access/AWS_SECRET_ACCESS_KEY"
      }
    ],
    "rules": [
      {
        "className":"com.boozallen.aissemble.configuration.UseLimitation",
        "configurations":{
            "maxUses": "5"
        }
      },
      {
        "className":"com.boozallen.aissemble.configuration.TimeLimitation",
        "configurations":{
            "expirationDate": "5 Days"
        }
      }
    ],
    "regeneration_method": [
      {
        "className":"com.example.AWSCredsRefresh",
        "configurations":{
            "endpoint": "https://my-new-token-service.org/getNewToken?exp=5days"
        }
      }
    ]
  }
]
----
In this example, both rules will be run when either property in `targets` is accessed. In the event that either rule determines the
property should be refreshed, then the regeneration method `AWSCredsRefresh` will be called. This method is responsible for returning 
the updated values for whichever properties it deems necessary.

////
TODO: Add details on creating rules and regeneration_method classes
////
