###
# #%L
# AIOps Docker Baseline::AIOps Metadata Service
# %%
# Copyright (C) 2021 Booz Allen
# %%
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# #L%
###
kafka.bootstrap.servers=kafka-cluster:9093

# configs to listen for messages from the metadata-ingest topic
mp.messaging.incoming.metadata-ingest.connector=smallrye-kafka
mp.messaging.incoming.metadata-ingest.group.id=MetadataIngest
mp.messaging.incoming.metadata-ingest.topic=metadata-ingest
mp.messaging.incoming.metadata-ingest.value.deserializer=com.boozallen.aiops.metadata.MetadataModelDeserializer
mp.messaging.incoming.metadata-ingest.auto.offset.reset=earliest

quarkus.vertx.max-event-loop-execute-time=30s
