{{- if .Values.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: elastic-user-secret
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace}}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.basicAuth.user.username }}
  password: {{ .Values.basicAuth.user.password }}
  roles: {{ .Values.basicAuth.user.roles }}
{{- end }}