{{- if not (eq .Values.sparkConf "") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-spark-config
data:
  sparkConf:
    {{- toYaml .Values.sparkConf | nindent 8 }}
{{- end }}
