# This file contains the default values for the aiSSEMBLE Spark History Helm chart.
app:
  # Sets labels for app.kubernetes.io/name Default is Chart.Name (aissemble-spark-history-chart)
  name: ''

enable: true

deployment:
  annotations: {}
  labels: {}
  replicas: 1
  image:
    repository: "ghcr.io/boozallen/aissemble-spark"
    imagePullPolicy: IfNotPresent
    tag: ""
  command: ["/opt/spark/sbin/start-history-server.sh"]
  env:
    SPARK_NO_DAEMONIZE: "true"
  envFromSecret: {}
  volumes: []
  volumeMounts: []
  tolerations: []
  affinity: {}

dependencies:
  packages: []
  jars: []

service:
  annotations: {}
  type: LoadBalancer
  port:
    name: "shs-http"
    port: 18080
    targetPort: 18080

ingress:
  enabled: true
  metadata:
    annotations: {}
  ingressClassName: nginx
  hosts:
    - paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: spark-history
              port:
                number: 18080

eventVolume:
  enabled: false
  name: "spark-events"
  mountPath: "/tmp/spark-events"
  storageType: "local"
  accessModes:
    - ReadWriteMany
  mountOptions:
    - allow-delete
  size: 1Gi
  volumePathOnNode: /tmp

sparkConf: |-
