# Default values for aissemble-jenkins.
jenkins:
  controller:
    image: ghcr.io/boozallen/aissemble-jenkins-controller
    # note the official chart does not use the controller tag value for testing, so disabling here
    testEnabled: false
    tag: "1.9.0-SNAPSHOT"
  agent:
    image: ghcr.io/boozallen/aissemble-jenkins-agent
    tag: "1.9.0-SNAPSHOT"
