<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.boozallen.aissemble</groupId>
        <artifactId>extensions-docker</artifactId>
        <version>2.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>aissemble-spark-infrastructure</artifactId>
    <name>aiSSEMBLE::Extensions::Docker::Spark Infrastructure</name>
    <description>A base Spark History and Thrift service</description>

    <packaging>docker-build</packaging>

    <properties>
        <dockerbuild.jars.directory>target/dockerbuild/jars/</dockerbuild.jars.directory>
        <version.delta.hive.connector>0.6.0</version.delta.hive.connector>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.boozallen.aissemble</groupId>
            <artifactId>aissemble-spark</artifactId>
            <version>${project.version}</version>
            <type>docker-build</type>
        </dependency>
        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-aws</artifactId>
            <version>${version.hadoop}</version>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>bundle</artifactId>
            <version>${version.aws.sdk.bundle}</version>
        </dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>${version.mysql-connector}</version>
        </dependency>
        <dependency>
            <groupId>io.delta</groupId>
            <artifactId>delta-spark_2.12</artifactId>
            <version>${version.delta}</version>
        </dependency>
        <dependency>
            <groupId>io.delta</groupId>
            <artifactId>delta-storage</artifactId>
            <version>${version.delta}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>${group.fabric8.plugin}</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <configuration>
                    <images>
                        <image>
                            <build>
                                <args>
                                    <JARS_DIR>${dockerbuild.jars.directory}</JARS_DIR>
                                    <DELTA_HIVE_CONNECTOR_VERSION>${version.delta.hive.connector}</DELTA_HIVE_CONNECTOR_VERSION>
                                </args>
                            </build>
                        </image>
                    </images>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
                <executions>
                    <execution>
                      <id>install-dockerfile</id>
                      <phase>install</phase>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <configuration>
                    <outputDirectory>${dockerbuild.jars.directory}</outputDirectory>
                    <includeTypes>jar</includeTypes>
                    <excludeTransitive>true</excludeTransitive>
                </configuration>
                <executions>
                    <execution>
                        <id>unpack</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>integration-test</id>
            <build>
                <plugins>
                    <!-- download Apache Derby jars -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-dependency-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>copy-derby-jars</id>
                                <phase>pre-integration-test</phase>
                                <goals>
                                    <goal>copy</goal>
                                </goals>
                                <configuration>
                                    <stripVersion>true</stripVersion>
                                    <artifactItems>
                                        <artifactItem>
                                            <groupId>org.apache.derby</groupId>
                                            <artifactId>derby</artifactId>
                                            <version>10.14.2.0</version>
                                            <destFileName>derby.jar</destFileName>
                                            <outputDirectory>${project.build.directory}</outputDirectory>
                                        </artifactItem>
                                    </artifactItems>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>${group.fabric8.plugin}</groupId>
                        <artifactId>docker-maven-plugin</artifactId>
                        <configuration>
                            <buildArchiveOnly>false</buildArchiveOnly>
                        </configuration>
                        <executions>
                            <execution>
                                <id>test-image</id>
                                <phase>integration-test</phase>
                                <configuration>
                                    <images>
                                        <image>
                                            <run>
                                                <entrypoint>sh -c /tmp/test/image-test.sh</entrypoint>
                                                <wait>
                                                    <http>
                                                        <!-- History server check -->
                                                        <url>http://localhost:${host.port}</url>
                                                    </http>
                                                    <!-- Thrift server check -->
                                                    <log>.*HiveThriftServer2 started.*</log>
                                                </wait>
                                                <ports>
                                                    <port>host.port:18080</port>
                                                </ports>
                                                <volumes>
                                                    <bind>
                                                        <volume>${project.basedir}/src/test/resources:/tmp/test</volume>
                                                        <volume>${project.build.directory}/derby.jar:/opt/spark/jars/derby.jar</volume>
                                                    </bind>
                                                </volumes>
                                            </run>
                                        </image>
                                    </images>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>test-image-cleanup</id>
                                <phase>post-integration-test</phase>
                            </execution>
                            <execution>
                                <id>test-image-cleanup-db</id>
                                <phase>post-integration-test</phase>
                                <configuration>
                                    <executable>docker</executable>
                                    <arguments>
                                        <argument>rm</argument>
                                        <argument>-f</argument>
                                        <argument>hive-metastore-db</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
