{{- $serviceAccountName := (index .Values "aissemble-quarkus-chart" "deployment" "serviceAccountName") -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName | default "pipeline-invocation-service" }}