########################################
## CONFIG | Airflow Configs
########################################
airflow:
  airflowVersion: 2.9.3

  executor: KubernetesExecutor

  statsd:
    enabled: false

  triggerer:
    enabled: false

  redis:
    enabled: false

  logs:
    persistence:
      enabled: true
      size: 500Mi
      
  webserver:
    args: ["bash", "-c", "exec airflow webserver --port 10080"]
    service:
      type: ClusterIP
      ports:
        - name: "http-1"
          port: 9085
          targetPort: airflow-ui
        - name: "http-2"
          port: 5000
          targetPort: airflow-ui
    defaultUser:
      enabled: true
      role: Admin
      username: admin
      password: aiops
      email: adminbah@someurl.com
      firstName: Booz
      lastName: Allen
    
  securityContext:
    runAsUser: 50000
    runAsGroup: 0
    fsGroup: 0

  ports:
    airflowUI: 10080

  env:
    - name: KRAUSENING_BASE
      value: /opt/airflow/config/
    - name: KAFKA_BOOTSTRAP_SERVER
      value: kafka-cluster:9093
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: GIT_PYTHON_REFRESH
      value: quiet

  volumeMounts:
    # Update the path to the model directory from the training pipeline
    - mountPath: /tmp/model
      name: model
    - mountPath: /notebooks/boms
      name: boms-notebook

  volumes:
    - name: model
      persistentVolumeClaim:
        claimName: model
    - name: boms-notebook
      persistentVolumeClaim:
        claimName: boms-notebook
