<?xml version="1.0" encoding="UTF-8"?>
<!--
  #%L
  aiSSEMBLE::Foundation::Upgrade
  %%
  Copyright (C) 2021 Booz Allen
  %%
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  #L%
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <parent>
        <groupId>org.test</groupId>
        <artifactId>swc-docker</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>swc-spark-worker-docker</artifactId>

    <packaging>docker-build</packaging>

    <name>Test Project::Docker::Spark</name>
    <description>Build for a Spark Docker container which contains all pipelines</description>
    <modelVersion>4.0.0</modelVersion>

    <build>
        <plugins>
            <plugin>
                <groupId>org.technologybrewery.fermenter</groupId>
                <artifactId>fermenter-mda</artifactId>
                <configuration>
                    <basePackage>com.boozallen.aiops.cookbook</basePackage>
                    <profile>aissemble-spark-worker-docker</profile>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-docker-resources</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.basedir}/src/main/resources/docker</directory>
                                    <filtering>false</filtering>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.boozallen.aissemble</groupId>
                <artifactId>mda-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-pipeline-artifacts</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy-pipeline-artifacts</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <groupId>${project.groupId}</groupId>
                    <modelsArtifactId>swc-pipeline-models</modelsArtifactId>
                    <pipelinesDirectory>${project.parent.parent.basedir}/swc-pipelines/</pipelinesDirectory>
                    <outputDirectory>${project.build.directory}/dockerbuild/</outputDirectory>
                    <habushuArtifactVersion>${version.habushu.dist.artifact}</habushuArtifactVersion>
                    <targetPipelineTypes>
                        <targetPipelineType>data-flow</targetPipelineType>
                    </targetPipelineTypes>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>${project.groupId}</groupId>
                        <artifactId>swc-pipeline-models</artifactId>
                        <version>${project.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>${group.fabric8.plugin}</groupId>
                <artifactId>docker-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.technologybrewery.habushu</groupId>
                <artifactId>habushu-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>dockerize</id>
                        <goals>
                            <goal>containerize-dependencies</goal>
                        </goals>
                        <phase>prepare-package</phase>
                        <configuration>
                            <dockerfile>src/main/resources/docker/Dockerfile</dockerfile>
                            <dockerBuilderBase>root_habushu_builder</dockerBuilderBase>
                            <dockerFinalBase>${DOCKER_BASELINE_REPO_ID}boozallen/aissemble-spark:${VERSION_AISSEMBLE}</dockerFinalBase>
                            <dockerUser>spark</dockerUser>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>my-py-spark-pipeline</artifactId>
            <version>${project.version}</version>
            <type>habushu</type>
        </dependency>
    </dependencies>
</project>

