= Data Lineage

== Overview
Data lineage represents the origins, movements, transformations, and flows of data.  It provides high processing
visibility to data scientists and engineers for simplified tracking of the full data
lifecycle.  Its granularity can vary and be specified to the needs of a particular project at a particular time.

== Leveraging Data Lineage
In order to integrate data lineage into your aiSSEMBLE(TM)-based project, you only need to opt-in through your pipeline
model definition, as described in the xref:pipeline-metamodel.adoc[detailed pipeline options].  aiSSEMBLE's factory
will create your pipeline with the necessary dependencies, as well as convenient stubs!

Data lineage is a rapidly evolving industry topic, with new and improved standards and formats emerging frequently.  We
provide generic types, capable of representing any lineage metadata, which can self-convert to and from other formats,
such as the https://openlineage.io[OpenLineage] standard.  We also provide functions for conveying your data lineage
throughout your aiSSEMBLE-powered ecosystem, such as via Kafka messaging.

=== Data Lineage Types & Objects

Our data lineage modules are modeled after the OpenLineage format.  We provide the following basic representation types:

* `Facet`
* `Dataset`, `InputDataset`, and `OutputDataset`
* `Job` and `Run`

==== Facets
A `Facet` describes some element of a data lineage action or entity.  `Runs`, `Jobs`, and `Datasets` can all have facets,
though not all facets would make sense on each.  For instance, one could construct a `Facet` to represent the source of
a given `Dataset`.

The `Facet` type provided by aiSSEMBLE is intentionally generic.  It can be extended within your project to construct
your own customized `Facets`, or it can be created directly from OpenLineage facets using the `from_open_lineage_facet`
function.  Custom `Facets` should override the appropriate conversion methods, such as `get_open_lineage_facet`, to address
specific conversion needs.

Facets are described by OpenLineage-format JSON schemas, and expect an URI string representing the path to that schema
as their only required argument.

Example construction of `Facet` objects:

```python
from aissemble_data_lineage import Facet, from_open_lineage_facet
from openlineage.client.facet import DataSourceDatasetFacet

my_facet = Facet("http://my_schema_url.org/my_schema.json")
converted_facet = from_open_lineage_facet(DataSourceDatasetFacet(name="dataset_name", uri="http://my_datasource"))
```

```java
import io.openlineage.client.OpenLineage;

OpenLineage openLineage = new OpenLineage(producer);
OpenLineage.RunFacets runFacets = openLineage.newRunFacetsBuilder().build();
```

To define your own custom `Facet`, you will need to create a new class that extends OpenLineage's `BaseFacet` and define
the attributes that the `Facet` will track. You can then use the `from_open_lineage_facet` function to set the values
of the custom `Facet`.

Example construction of a customized `Facet` object:
```python
from aissemble_data_lineage import from_open_lineage_facet
from openlineage.client.facet import BaseFacet
import attr

@attr.s
class MyCustomFacet(BaseFacet):
    custom_attr: str = attr.ib()
    _additional_skip_redact: ["custom_attr"]

    def __init__(self, custom_attr):
        super().__init__()
        self.custom_attr = custom_attr

custom_facet = from_open_lineage_facet(MyCustomFacet(custom_attr = "Custom Value"))
```

==== Datasets
`Dataset` objects represent just that-- A known collection of data following a common path through the processing system.
For cases where inputs and outputs are distinctive from processed data, we provide the `InputDataset` and `OutputDataset`
objects.

Example construction of `Dataset` objects:

```python
from aissemble_data_lineage import Dataset, InputDataset, OutputDataset

my_dataset = Dataset(name="dataset_1", facets={"facet_1": my_facet})
my_input_dataset = InputDataset(name="dataset_2", facets={}, input_facets={})
my_output_dataset = OutputDataset(name="dataset_3", facets={}, output_facets={})
```

```java
import io.openlineage.client.OpenLineage.InputDataset;

ArrayList<InputDataset> olInputs = new ArrayList<>();
    if(inputs != null) {
        inputs.forEach(input -> {
            olInputs.add((InputDataset) input.getOpenLineageDataset());
        });
    }
```

==== Runs
A `Run` is composed of one to many `Jobs`, and encompasses exactly one full processing pass over your data.

Example construction of `Run` objects:
```python
from aissemble_data_lineage import Run
from uuid import uuid4

my_run = Run(uuid4(), facets={})
```

```java
import com.boozallen.aissemble.data.lineage.Run;

Run olRun = run.getOpenLineageRun();
```

==== Jobs
A `Job` represents a single discrete step in the data processing pipeline, such as ingestion, a specific transformation,
or any other action of note.

Example construction of `Job` objects:
```python
from aissemble_data_lineage import Job

my_job = Job("my_job", facets={})
```

```java
import com.boozallen.aissemble.data.lineage.Job;

Run olJob = run.getOpenLineageJob();
```

== Additional Resources
The full aiSSEMBLE data lineage source code can be reviewed on
https://github.com/boozallen/aissemble/tree/dev/foundation/foundation-lineage/foundation-data-lineage[GitHub].

The Python methods detailing the generation of minimal instances of `Run`, `Jo`b, and `RunEvent `for emission are described
in `src/<pipeline-name>/generated/step/abstract_data_action.py`. Correspondingly, the Java methods outlining the same
are detailed in `src/generated/java/<package-name>/AbstractPipelineStep.java`.
