= Data Access

== Overview
Data access is the process of exposing data to external consumers. aiSSEMBLE(TM) supports this through generated
services and records.

== What Gets Generated
Data access is xref:pipeline-metamodel.adoc#_pipeline_metamodel[enabled by default] for projects that include at least
one record. When enabled, aiSSEMBLE generates a https://graphql.org/learn/[GraphQL,role=external,window=_blank] query
service with endpoints for retrieving records from ingested datasets.

|===
|Generated file | Description

|`<project>/<project>-pipelines/<project>-data-access/pom.xml`
|Creates the Maven module that builds the generated query service.

|`<project>/<project>-pipelines/<project>-data-access/src/main/resources/application.properties`
|https://quarkus.io/guides/config[Quarkus,role=external,window=_blank] configuration of the query service.

|`<project>/<project>-pipelines/<project>-data-access/src/main/java/com/test/DataAccessResource.java`
|GraphQL resource that exposes the /graphql REST endpoint for data access requests.
|===

=== GraphQL API
GraphQL queries are generated based on the record metamodel(s) in `<project>/<project>-pipeline-models/src/main/resources/records/`.
By default, two queries are generated for each record metamodel: one for retrieving all the results from a table, and
one for retrieving a limited number of results from a table. The methods that implement these queries can be found in
`<project>/<project>-pipelines/<project>-data-access/src/generated/java/<user-defined-package>/DataAccessResourceBase.java`.
These methods can be overridden, or new queries can be added by modifying
`<project>/<project>-pipelines/<project>-data-access/src/main/java/<user-defined-package>/DataAccessResource.java`


.GraphQL query to pull records from a given table:
[source,json]
----
query auditList {
    TaxPayer(table: delinquent_tax_payers)
    {
        id
    }
}
----

|===
|Element | Element Type | Element Description

|`auditList`
|Operation name
|Name of the query. The name assigned to this operation has no correlation to the pipeline or metamodel, this is
simply based on your choosing.

|`TaxPayer`
|Query object
|The type of record that you are pulling from data store. This name is derived from your record metamodel.

|`delinquent_tax_payers`
|Argument
|Name of the table being queried. In the execution of the data pipeline, your records are stored in a table with the
name you specified in your step implementation.

|`id` (String)
|Variable
|Field from the record type being returned. The available fields correspond with the fields within your record metamodel.
|===

.GraphQL query to pull records from a given table with a limit:
[source,json]
----
query auditList {
    TaxPayerLimited(table: delinquent_tax_payers, limit: 10)
    {
        id
    }
}
----

|===
|Element | Element Type | Element Description

|`auditList`
|Operation name
|Name of the query. The name assigned to this operation has no correlation to the pipeline or metamodel, this is
simply based on your choosing.

|`TaxPayerLimited`
|Query object
|The type of record that you are pulling from data store. This name is derived from your record metamodel.

|`delinquent_tax_payers`
|Argument
|Name of the table being queried. In the execution of the data pipeline, your records are stored in a table with the name
you specified in your step implementation.

|`limit` (int)
|Argument
|Field from the record type being returned. The available fields correspond with the fields within your record metamodel.

|`id` (String)
|Variable
|Limit on how many records is to be returned from the query.
|===

To invoke the GraphQL query, you will need to do so via a REST API call.

=== POST/graphql
.Returns the records for the given GraphQL query.
[%collapsible]
====
// .POST/graphql
// Returns the records for the given GraphQL query.

*Parameters*

|===
|*Name* | *Description*
|`query`
|https://graphql.org/learn/queries/[GraphQL query,role=external,window=_blank] executed to retrieve the data.
|===

*Return*
[cols="1,1"]
|===
|`\{record-name}` records.
|List of records. The record will be based on your record metamodel.
|===


.Sample data input:
[source,JSON]
----
{
    "query": "{ ExampleDataLimited(table: \" example_table \", limit: 10) { id } }"
}
----

.Sample data output:
[source,JSON]
----
{
    "data": {
        "ExampleData": []
    }
}
----
====

=== Deployment Artifacts
Once a data access record has been defined, aiSSEMBLE will also generate deployment artifacts like Docker images,
Kubernetes manifests, and Tilt configurations. For more information, see the
xref:containers.adoc#_containers[Containers] page.
