= Post-Training Actions

== Overview
Post-training actions can be specified in a machine-learning pipeline to apply additional post-training processing.
When one or more post-training actions are specified in a training step, scaffolding code is generated into the
training pipeline, and each post-training action is applied during the training run after the model is trained.
This page is intended to assist in understanding the generated components that are included when post-training
actions are specified.

== What Gets Generated

For details on how to specify post-training actions, please see the
xref:pipeline-metamodel.adoc#_pipeline_step_post_actions_element_options[Pipeline Step Post Actions Element Options].

=== Model Conversion Post-Training Action

A model-conversion post-training action can be used to convert the trained model to another model format. Below will
describe the scaffolding code that is generated for a model-conversion post-training action.

==== ONNX

The following example post-training action will be used to describe what gets generated for ONNX model conversion:

.Example ONNX Model Conversion Post-Training Action
[source,json]
----
{
    "name": "ConvertModelToOnnxFormat",
    "type": "model-conversion",
    "modelTarget": "onnx",
    "modelSource": "sklearn"
}
----

[cols="2,4a"]
|===
|File|Description

| `src/<python_package_name>/generated/post_action/onnx_sklearn_model_conversion_base.py`
| Base class containing core code for leveraging ONNX to convert sklearn models. This class is regenerated with
every build, and therefore cannot be modified.

The following methods are generated:

* `_convert` - performs the ONNX conversion.
* `_save` - saves the converted ONNX model.

In addition, ONNX conversion properties are generated with default values. These can be overridden in the
post-training action implementation class to specify custom values to pass to the ONNX conversion.

| `src/<python_package_name>/generated/post_action/convert_model_to_onnx_format_base.py`
| Post-training action base class containing core code for applying the post-training action. This class is
regenerated with every build, and therefore cannot be modified.

The following method is generated:

* `apply` - applies the ONNX conversion by calling the `_convert` and `_save` methods from the above class.

| `src/<python_package_name>/post_action/convert_model_to_onnx_format.py`
| Post-training action implementation class. This class is where properties and methods from the above base classes
can be overridden, if desired.

If the ONNX conversion has any required parameters, they will be generated here for manual implementation.

|===


==== Custom

The following example post-training action will be used to describe what gets generated for a custom model conversion:

.Example Custom Model Conversion Post-Training Action
[source,json]
----
{
    "name": "ConvertModelToCustomFormat",
    "type": "model-conversion",
    "modelTarget": "custom",
    "modelSource": "sklearn"
}
----

[cols="2,4a"]
|===
|File|Description

| `src/<python_package_name>/generated/post_action/custom_model_conversion_base.py`
| Base class containing core code for implementing a custom model conversion. This class is regenerated with every
build, and therefore cannot be modified.

The following methods are generated:

* `_convert` - abstract method to implement the custom conversion. This should be implemented in the post-training
action implementation class.
* `_save` - abstract method to implement the saving of the converted model. This should be implemented in the
post-training action implementation class.

| `src/<python_package_name>/generated/post_action/convert_model_to_custom_format_base.py`
| Post-training action base class containing core code for applying the post-training action. This class is
regenerated with every build, and therefore cannot be modified.

The following method is generated:

* `apply` - applies the cusom conversion by calling the `_convert` and `_save` methods from the above class.

| `src/<python_package_name>/post_action/convert_model_to_custom_format.py`
| Post-training action implementation class. This class is where the `_convert` and `_save` methods should be implemented.

|===

=== Freeform Post-Training Action

A freeform post-training action can be used to apply any custom post-training processing. The following example post-training action will be used to describe what gets generated for a freeform post-training action:

.Example Freeform Post-Training Action
[source,json]
----
{
    "name": "AdditionalProcessing",
    "type": "freeform"
}
----

[cols="2,4a"]
|===
|File|Description

| `src/<python_package_name>/generated/post_action/additional_processing_base.py`
| Post-training action base class containing core code for applying the post-training action. This class is
regenerated with every build, and therefore cannot be modified.

The following method is generated:

* `apply` - abstract method to implement the custom processing. This should be implemented in the post-training
action implementation class.

| `src/<python_package_name>/post_action/additional_processing.py`
| Post-training action implementation class. This class is where the `apply` method should be implemented.

|===