# Default values for fastapi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
app:
  # Sets labels for app.kubernetes.io/name Default is Chart.Name (aissemble-fastapi-chart)
  name: ''
  # Sets the labels for app.kubernetes.io/version. Default is Chart.AppVersion
  version: ''
replicaCount: 1
hostname: fastapi
image:
  name: boozallen/aissemble-fastapi
  tag: ""
  imagePullPolicy: Always
  dockerRepo: ghcr.io/

service:
  spec:
    ports:
      - name: http
        port: 8080
        targetPort: 80
deployment:
  ports:
    - name: http-1
      containerPort: 80
      protocol: TCP
  restartPolicy: Always
