<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.boozallen.aissemble</groupId>
        <artifactId>extensions</artifactId>
        <version>1.13.0-rc6</version>
    </parent>

    <artifactId>extensions-docker</artifactId>
    <name>aiSSEMBLE::Extensions::Docker</name>
    <packaging>pom</packaging>

    <properties>
        <docker.repo.id>ghcr.io</docker.repo.id>
        <dockerImageName>boozallen/${project.artifactId}</dockerImageName>
    </properties>

    <modules>
        <module>aissemble-quarkus</module>
        <module>aissemble-hive-service</module>
        <module>aissemble-jenkins</module>
        <module>aissemble-metadata</module>
        <module>aissemble-nvidia</module>
        <module>aissemble-policy-decision-point</module>
        <module>aissemble-spark</module>
        <module>aissemble-spark-infrastructure</module>
        <module>aissemble-spark-operator</module>
        <module>aissemble-versioning</module>
        <module>aissemble-model-training-api-containers</module>
        <module>aissemble-data-lineage-http-consumer</module>
        <module>aissemble-pipeline-invocation</module>
        <module>aissemble-configuration-store</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.boozallen.aissemble</groupId>
                <artifactId>bom-instantiation</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.technologybrewery.habushu</groupId>
                    <artifactId>habushu-maven-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>stage-python</id>
                            <goals>
                                <goal>containerize-dependencies</goal>
                            </goals>
                            <phase>prepare-package</phase>
                            <configuration>
                                <dockerfile>${project.basedir}/src/main/resources/docker/Dockerfile</dockerfile>
                                <dockerBuilderBase>docker.io/python:3.11</dockerBuilderBase>
                                <dockerFinalBase>docker.io/python:3.11-slim</dockerFinalBase>
                                <dockerUser>1001</dockerUser>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-install-plugin</artifactId>
                    <executions>
                        <execution>
                            <!-- Create an artifact associated with the docker-build packaging so that project
                                dependency resolving works with images that depend on other docker modules. This
                                execution will be activated by the actual docker builds by setting phase to install.-->
                            <id>install-dockerfile</id>
                            <phase>none</phase>
                            <goals>
                                <goal>install-file</goal>
                            </goals>
                            <configuration>
                                <groupId>${project.groupId}</groupId>
                                <artifactId>${project.artifactId}</artifactId>
                                <version>${project.version}</version>
                                <packaging>${project.packaging}</packaging>
                                <file>src/main/resources/docker/Dockerfile</file>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
    <profiles>
        <profile>
            <id>ensure-docker-dependencies</id>
            <!-- This profile is used to ensure that the docker dependencies are encoded in Maven properly. Because of
            the way docker works, any missing image will just be downloaded from the repository. This changes the repo
            such that the image will be missing from the remote.  To fully test the dependencies, you will also need
            to ensure that all of the `local/*` images are deleted from your docker image cache:
                `docker rmi -f $(docker images -q 'local/boozallen/*')`
            -->
            <properties>
                <docker.baseline.repo.id>local</docker.baseline.repo.id>
            </properties>
        </profile>
        <profile>
            <id>integration-test</id>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>${group.fabric8.plugin}</groupId>
                            <artifactId>docker-maven-plugin</artifactId>
                            <executions>
                                <execution>
                                    <id>test-image</id>
                                    <!-- Images with tests should set the phase of this execution to `integration-test` to activate it -->
                                    <phase>none</phase>
                                    <goals>
                                        <goal>start</goal>
                                    </goals>
                                    <configuration>
                                        <showLogs>true</showLogs>
                                        <images>
                                            <image>
                                                <run>
                                                    <containerNamePattern>${project.artifactId}-test</containerNamePattern>
                                                    <!-- If autoRemove is true, the build will fail.
                                                    See https://github.com/fabric8io/docker-maven-plugin/issues/1622 -->
                                                    <autoRemove>false</autoRemove>
                                                    <wait>
                                                        <time>60000</time>
                                                    </wait>
                                                </run>
                                            </image>
                                        </images>
                                    </configuration>
                                </execution>
                            </executions>
                        </plugin>
                        <plugin>
                            <groupId>org.codehaus.mojo</groupId>
                            <artifactId>exec-maven-plugin</artifactId>
                            <executions>
                                <execution>
                                    <id>test-image-cleanup</id>
                                    <!-- Images with tests should set the phase of this execution to `post-integration-test` to activate it -->
                                    <phase>none</phase>
                                    <goals>
                                        <goal>exec</goal>
                                    </goals>
                                    <configuration>
                                        <executable>docker</executable>
                                        <arguments>
                                            <argument>rm</argument>
                                            <argument>-f</argument>
                                            <argument>${project.artifactId}-test</argument>
                                        </arguments>
                                    </configuration>
                                </execution>
                            </executions>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>
        <profile>
            <id>gh-build</id>
            <properties>
                <docker.builder.name>${env.DOCKER_BUILDER_NAME}</docker.builder.name>
            </properties>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>${group.fabric8.plugin}</groupId>
                            <artifactId>docker-maven-plugin</artifactId>
                            <configuration>
                                <images>
                                    <image>
                                        <build>
                                            <buildx>
                                                <builderName>${docker.builder.name}</builderName>
                                            </buildx>
                                        </build>
                                    </image>
                                </images>
                            </configuration>
                            <executions>
                                <execution>
                                    <id>default-push</id>
                                    <configuration>
                                        <images>
                                            <image>
                                                <build>
                                                    <buildx>
                                                        <builderName>${docker.builder.name}</builderName>
                                                    </buildx>
                                                </build>
                                            </image>
                                        </images>
                                    </configuration>
                                </execution>
                            </executions>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>
    </profiles>
</project>
