[tool.poetry]
name = "aissemble-foundation-model-training-api"
version = "1.7.0"
description = ""
authors = ["aiSSEMBLE Baseline Community <aissemble@bah.com>"]
readme = "README.md"
packages = [
    {include = "model_training_api", from = "src"},
]

[tool.poetry.dependencies]
aissemble-foundation-messaging-python = {path = "../foundation-messaging/foundation-messaging-python/aissemble-foundation-messaging-python-client", develop = true}
python = ">=3.11.4, <3.12"
fastapi = ">=0.95.0"
uvicorn = {version = "^0.18.0", extras = ["standard"]}
pydantic = ">=1.8.0,<2.0.0"
kubernetes = ">=26.1.0"
urllib3 = "^1.26.18"
krausening = ">=19"

[tool.poetry.group.dev.dependencies]
black = ">=22.1.0"
behave = ">=1.2.6"
nose = ">=1.3.7"
kappa-maki = ">=1.0.1"
pylint = "^3.1.0"


[build-system]
requires = ["poetry-core>=1.7.0"]
build-backend = "poetry.core.masonry.api"