# Default values for metadata
app:
  # Sets labels for app.kubernetes.io/name Default is Chart.name (aissemble-metadata-chart)
  name: ''
  # Sets the labels for app.kubernetes.io/version. Default is Chart.appVersion
  version: ''

hostname: metadata
image:
  name: boozallen/aissemble-metadata
  imagePullPolicy: Always
  dockerRepo: ghcr.io/

service:
  spec:
    ports:
      - name: rest-api
        port: 8082
        targetPort: 8080

deployment:
  ports:
    - name: http-1
      containerPort: 8080
      protocol: TCP
  restartPolicy: Always

ingress:
  enabled: true
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
  hosts:
    - host: metadata-ai.boozallen.github.io
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: metadata
              port:
                number: 8082
  status: 10.192.83.167
