spec:
  sparkConf:
    spark.sql.extensions: "io.delta.sql.DeltaSparkSessionExtension,org.apache.sedona.sql.SedonaSqlExtensions"
    spark.sql.catalogImplementation: "hive"
    spark.sql.catalog.spark_catalog: "org.apache.spark.sql.delta.catalog.DeltaCatalog"
    spark.eventLog.dir: "s3a://spark-infrastructure/spark-events"
    spark.es.nodes: "elasticsearch-es-http"
    spark.es.port: "9200"

    # these values can be overridden in [YOUR-PROJECT]-deploy/src/main/resources/apps/elasticsearch/*.yaml
    spark.es.net.http.auth.user: "elastic"
    spark.es.net.http.auth.pass: "elastic"
    spark.serializer: "org.apache.spark.serializer.KryoSerializer"
    spark.kryo.registrator: "org.apache.sedona.viz.core.Serde.SedonaVizKryoRegistrator"
