---
name: aissemble-infrastructure-chart
# Version is automatically set by the plugin so this is only a placeholder
version: 1.0.0
apiVersion: v2
description: Baseline aiSSEMBLE Infrastructure chart -- see the extensions-helm directory in aiSSEMBLE for more details.
# App Version is automatically set by the plugin so this is only a placeholder
appVersion: 1.0.0
sources:
  - https://github.com/boozallen/aissemble
dependencies:
  - name: argo-cd
    version: 7.4.1
    repository: https://argoproj.github.io/argo-helm
    condition: argo-cd.enabled
  - name: jenkins
    version: 5.5.4
    repository: https://charts.jenkins.io
    condition: jenkins.enabled
  - name: ingress-nginx
    version: 4.11.1
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
