apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  quarkus-properties-file: |-
    {{- range $property := .Values.configMap.supplementalQuarkusConfig }}
      {{ $property }}
    {{- end }}