apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace}}
data:
  quarkus-properties-file: |-
    {{- range $property := .Values.configMap.supplementalQuarkusConfig }}
      {{ $property }}
    {{- end }}