apiVersion: v1
kind: ConfigMap
metadata:
  name: metastore-service-config
data:
  # Add all the default properties from the local values.yaml to the ConfigMap
  # Then check if there are any downstream properties and add them as well
  metastore-site.xml: |
    <configuration>
    {{- range $property := .Values.configMap.metastoreServiceConfig.baseProperties }}
      <property>
        <name>{{ $property.name }}</name>
        <value>{{ $property.value }}</value>

      {{- if $property.description }}
        <description>{{ $property.description }}</description>
      {{- end }}
      </property>
    {{- end }}

    {{- if .Values.configMap.metastoreServiceConfig.properties }}
      {{- range $property := .Values.configMap.metastoreServiceConfig.properties }}
      <property>
        <name>{{ $property.name }}</name>
        <value>{{ $property.value }}</value>

        {{- if $property.description }}
        <description>{{ $property.description }}</description>
        {{- end }}
      </property>
      {{- end }}
    {{- end }}
    </configuration>
