# Base Kubernetes deployment artifact.
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Values.app.name | default .Chart.Name }}
    app.kubernetes.io/name: {{ .Values.app.name | default .Chart.Name }}
  name: {{ .Values.app.name | default .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Values.app.name | default .Chart.Name }}
      app.kubernetes.io/name: {{ .Values.app.name | default .Chart.Name }}
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Values.app.name | default .Chart.Name }}
        app.kubernetes.io/name: {{ .Values.app.name | default .Chart.Name }}
    spec:
      {{- with .Values.deployment.securityContext }}
      securityContext:
        {{- toYaml . | nindent 12}}
      {{- end }}
      serviceAccountName: {{ .Values.deployment.serviceAccountName }}
      automountServiceAccountToken: {{ .Values.deployment.automountServiceAccountToken | default false }}
      {{- with .Values.deployment.volumes }}
      volumes:
        {{- toYaml . | nindent 12}}
      {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 12}}
      {{- end }}
      initContainers:
        - name: "init-or-upgrade-schema"
          image: {{ .Values.image.dockerRepo }}{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          command:
            - "/opt/hive/bin/schematool"
            - "-dbType"
            - {{ .Values.hive.dbType }}
            - "-initOrUpgradeSchema"
            - "--verbose"
          volumeMounts:
          - name: metastore-service-config
            mountPath: /opt/hive/conf/metastore-site.xml
            subPath: metastore-site.xml
      containers:
        - name: {{ .Values.app.name | default .Chart.Name }}
          image: {{ .Values.image.dockerRepo }}{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          env:
            {{- toYaml .Values.deployment.baseEnv | nindent 12}}
          {{- if .Values.deployment.env}}
            {{- toYaml .Values.deployment.env | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12}}
          {{- end }}
          {{- with .Values.deployment.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.deployment.command }}
          command: {{ .Values.deployment.command }}
          {{- end }}
      hostname: {{ .Values.hostname }}
      restartPolicy: {{ .Values.deployment.restartPolicy }}
      {{- with .Values.deployment.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
