mlflow:
  postgresql:
    enabled: false
  minio:
    enabled: false
  run:
    enabled: false
  tracking:
    auth:
      enabled: false
    service:
      type: ClusterIP
      ports:
        http: 5005
  externalDatabase:
    host: postgres
    port: 5432
    user: postgres
    password: password
    database: db