mlflow:
  image:
    # NB: will soon be updated to public mlflow image - but waiting to upgrade across the application, so point to the
    # 2.3.1 image that was part of aissemble 1.7.0 in the meantime. TODO in https://github.com/boozallen/aissemble/issues/226
    registry: ghcr.io
    repository: boozallen/aissemble-mlflow
    tag: 1.7.0
  postgresql:
    enabled: false
  minio:
    enabled: false
  run:
    enabled: false
  tracking:
    auth:
      enabled: false
    service:
      type: ClusterIP
      ports:
        http: 5005
  externalDatabase:
    host: postgres
    port: 5432
    user: postgres
    password: password
    database: db