# Data Access
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
aissemble-quarkus:
  service:
    ports:
      - name: http
        port: 8081
        protocol: TCP
        targetPort: 8080
  deployment:
    ports:
      - name: http-1
        containerPort: 8081
        protocol: TCP
    env:
      - name: DATA_ACCESS_GRAPHQL_PORT_EXTERNAL
        value: "http-1"
      - name: DATA_ACCESS_GRAPHQL_HOST_EXTERNAL
        value: "data-access"

