{{- if .Values.credentialSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentialSecret.name }}
stringData:
  AWS_ACCESS_KEY_ID: "123"
  AWS_SECRET_ACCESS_KEY: "456"
{{- end }}