---
name: aissemble-spark-operator-chart
# Version is automatically set by the plugin so this is only a placeholder
version: 1.0.0
apiVersion: v2
description: Baseline Spark Operator chart -- see the extensions-helm directory in aiSSEMBLE for more details.
# App Version is automatically set by the plugin so this is only a placeholder
appVersion: 1.0.0
sources:
  - https://github.com/boozallen/aissemble
dependencies:
  - name: spark-operator
    version: 1.1.27
    repository: https://kubeflow.github.io/spark-operator/
    import-values:
      - child: batchScheduler
        parent: batchScheduler
      - child: webhook
        parent: webhook