# findExecPattern 1: find requirements.txts, python pip install
RUN set -e && files=$(find /tmp/requirements -path '/tmp/requirements/*/*' -name requirements.txt -type f); for file in $files; do python3 -m pip install --no-cache-dir -r $file || exit 1; done;
RUN set -e && files=$(find /installation/requirements -path '/installation/requirements/*/*/*' -name requirements.txt -type f); for file in $files; do "$VENV/bin/python3" -m pip install --no-cache-dir -r $file || exit 1; done;

# findExecPattern 2: find tarballs, python pip install
RUN set -e && files=$(find /installation/${trainingModule}/ -name *.tar.gz -type f); for file in $files; do python3.11 -m pip install --no-deps --no-cache-dir $file || exit 1; done;
RUN set -e && files=$(find /opt/spark/jobs -path '/opt/spark/jobs/pipelines/*/*' -name '*.tar.gz' -type f); for file in $files; do python3 -m pip install --no-deps --no-cache-dir $file || exit 1; done;
RUN set -e && files=$(find $AIRFLOW_HOME/pipelines -path "$AIRFLOW_HOME/pipelines/*/*/*" -name *.tar.gz -type f); for file in $files; do "$VENV/bin/python3" -m pip install --no-deps --no-cache-dir $file || exit 1; done;

# findExecPattern 3: find wheels, python pip install
RUN set -e && files=$(find /tmp/wheels -path '/tmp/wheels/*' -name '*.whl' -type f); for file in $files; do python3 -m pip install --no-cache-dir $file || exit 1; done;

# forDoPattern 1: cd into modules, for x in wheel, pip install
RUN set -e && cd /modules/${trainingModule}; for x in *.whl; do pip install $x --no-cache-dir --no-deps; done
RUN set -e && cd /modules/${inferenceModule}; for x in *.whl; do python -m pip install $x --no-cache-dir --no-deps; done