{{ if .Values.webhook.enable }}
{{- $appName := (index .Values "aissemble-quarkus-chart" "app" "name") -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $appName }}-webhook-cleanup
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ $appName }}-webhook-cleanup
    spec:
      serviceAccountName: {{ .Values.webhook.serviceAccount.name }}
      restartPolicy: OnFailure
      containers:
      - name: clean-webhook
        image: curlimages/curl:latest
        imagePullPolicy: {{ index .Values "aissemble-quarkus-chart" "deployment" "image" "imagePullPolicy"}}
        command:
        - "/bin/sh"
        - "-c"
        - "curl -ik \
          -X DELETE \
          -H \"Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\" \
          -H \"Accept: application/json\" \
          -H \"Content-Type: application/json\" \
          https://kubernetes.default.svc/apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations/{{ .Values.webhook.name }} \
        {{- if .Values.webhook.certSecret.create }}
          && \
          curl -ik \
          -X DELETE \
          -H \"Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\" \
          -H \"Accept: application/json\" \
          -H \"Content-Type: application/json\" \
          https://kubernetes.default.svc/api/v1/namespaces/{{ .Release.Namespace }}/secrets/{{ .Values.webhook.certSecret.name }}
        {{- end }}
          && \
          curl -ik \
          -X DELETE \
          -H \"Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\" \
          -H \"Accept: application/json\" \
          -H \"Content-Type: application/json\" \
          --data \"{\\\"kind\\\":\\\"DeleteOptions\\\",\\\"apiVersion\\\":\\\"batch/v1\\\",\\\"propagationPolicy\\\":\\\"Foreground\\\"}\" \
          https://kubernetes.default.svc/apis/batch/v1/namespaces/{{ .Release.Namespace }}/jobs/{{ index .Values "aissemble-quarkus-chart" "app" "name" }}-webhook-init"
{{ end }}