<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.boozallen.aissemble</groupId>
        <artifactId>foundation-drift-detection</artifactId>
        <version>2.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <name>aiSSEMBLE::Foundation::Drift Detection::Python Rest Client</name>
    <artifactId>aissemble-foundation-drift-detection-client-python</artifactId>
    <description>The drift detection Python rest client has the ability to invoke drift services using Python
    </description>
    <packaging>habushu</packaging>

<!--    UNCOMMENT ONCE TEST STEPS ARE ADDED-->
<!--    ALSO ADD THE PLUGIN-->
<!--    <dependencies>-->
<!--        <dependency>-->
<!--            <groupId>net.masterthought</groupId>-->
<!--            <artifactId>cucumber-reporting</artifactId>-->
<!--        </dependency>-->
<!--    </dependencies>-->

    <dependencies>
        <dependency>
            <groupId>com.boozallen.aissemble</groupId>
            <artifactId>foundation-drift-detection-service</artifactId>
            <version>${project.version}</version>
            <classifier>app</classifier>
            <type>zip</type>
            <scope>test</scope>
            <!-- jars are already packaged in zip -->
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <build>
        <directory>dist</directory>
        <plugins>
            <plugin>
                <groupId>org.technologybrewery.habushu</groupId>
                <artifactId>habushu-maven-plugin</artifactId>
                <configuration>
                    <behaveOptions>--tags ~integration</behaveOptions>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>license-maven-plugin</artifactId>
                <configuration>
                    <licenseFile>LICENSE</licenseFile>
                </configuration>
            </plugin>
<!--            UNCOMMENT ONCE TEST STEPS ARE ADDED-->
<!--            ALSO ADD THE DEPENDENCY-->
<!--            <plugin>-->
<!--                <groupId>net.masterthought</groupId>-->
<!--                <artifactId>maven-cucumber-reporting</artifactId>-->
<!--            </plugin>-->
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>integration-test</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.technologybrewery.habushu</groupId>
                        <artifactId>habushu-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>integration-tests</id>
                                <phase>integration-test</phase>
                                <goals>
                                    <goal>behave-bdd-test</goal>
                                </goals>
                                <configuration>
                                    <behaveOptions>--tags integration</behaveOptions>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-dependency-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>unpack-service-app</id>
                                <phase>pre-integration-test</phase>
                                <goals>
                                    <goal>unpack-dependencies</goal>
                                </goals>
                                <configuration>
                                    <outputDirectory>${project.build.directory}</outputDirectory>
                                    <failOnMissingClassifierArtifact>true</failOnMissingClassifierArtifact>
                                    <includeClassifiers>app</includeClassifiers>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>com.bazaarvoice.maven.plugins</groupId>
                        <artifactId>process-exec-maven-plugin</artifactId>
                        <version>0.7</version>
                        <executions>
                            <execution>
                                <id>foundation-drift-detection-service</id>
                                <phase>pre-integration-test</phase>
                                <goals>
                                    <goal>start</goal>
                                </goals>
                                <configuration>
                                    <name>DriftDetectionService</name>
                                    <waitForInterrupt>false</waitForInterrupt>
                                    <healthcheckUrl>http://localhost:8084/invoke-drift/healthcheck</healthcheckUrl>
                                    <arguments>
                                        <argument>java</argument>
                                        <argument>-DKRAUSENING_BASE=${basedir}/tests/resources/config/</argument>
                                        <argument>-DDRIFT_DETECTION_POLICIES=${basedir}/tests/resources/drift-policies</argument>
                                        <argument>-Dquarkus.http.port=8084</argument>
                                        <argument>-jar</argument>
                                        <argument>${project.build.directory}/quarkus-app/quarkus-run.jar</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                            <execution>
                                <id>stop-all</id>
                                <phase>post-integration-test</phase>
                                <goals>
                                    <goal>stop-all</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>