apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configmap-rolebinding-github-action
subjects:
  - kind: User
    name: arc-runner-set-aissemble-gha-rs-no-permission
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: configmap-manager
  apiGroup: rbac.authorization.k8s.io


