name: Release aissemble

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release Version (X.Y.Z)"
        required: true
        type: string
      developmentVersion:
        description: "Next Dev Version"
        required: true
        type: string
      releaseBranch:
        description: "Release Branch (default: aissemble-release-X.Y)"
        required: false
        type: string

permissions:
  contents: write # Requires 'write' to update Antora docs
  packages: write

jobs:
  build:

    runs-on: arc-runner-set-aissemble
    env:
      RELEASE_VERSION: ${{ inputs.releaseVersion }}
      NEXT_DEVELOPMENT_VERSION: ${{ inputs.developmentVersion }}
      RELEASE_BRANCH: ${{ inputs.releaseBranch }}
      DOCKER_BUILDER_NAME: k8s-multiarch

    steps:
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
      - uses: actions/checkout@v4
      - name: Split version
        id: split_version
        uses: ./.github/actions/split_version
        with:
          version: ${{ env.RELEASE_VERSION }}
          release-branch: ${{ env.RELEASE_BRANCH }}
      - name: Print release parameters
        run: | 
          echo "Releasing with the following parameters"
          echo "Release version: ${{ env.RELEASE_VERSION }}"
          echo "Next Development version: ${{ env.NEXT_DEVELOPMENT_VERSION }}"
          echo "Major minor version: ${{ steps.split_version.outputs.major-minor-version }}"
          echo "Patch Version: ${{ steps.split_version.outputs.patch-version }}"
          echo "Is pre release version: ${{ steps.split_version.outputs.is-pre-release }}"
          echo "Release branch: ${{ steps.split_version.outputs.release-branch }}"
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.split_version.outputs.release-branch }}
      - name: Update Antora Docs
        uses: ./.github/actions/update_antora
        with:
          version: ${{ env.RELEASE_VERSION }}
          major-minor-version: ${{ steps.split_version.outputs.major-minor-version }} 
          patch-version: ${{ steps.split_version.outputs.patch-version }}
          is-pre-release: ${{ steps.split_version.outputs.is-pre-release }}
          release-branch: ${{ steps.split_version.outputs.release-branch }}
          custom-facet-new-version: ${{ env.RELEASE_VERSION }}
      - name: Install dependencies
        uses: ./.github/actions/install_dependencies
        with:
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Provision Docker builder
        id: provision-docker-builder
        run: |
          docker builder create --name=$DOCKER_BUILDER_NAME \
                                --bootstrap \
                                --driver=kubernetes \
                                --platform=linux/amd64 \
                                --driver-opt="nodeselector=kubernetes.io/arch=amd64","image=docker.io/moby/buildkit:v0.19.0"
          docker builder create --name=$DOCKER_BUILDER_NAME \
                                --append \
                                --bootstrap \
                                --driver=kubernetes \
                                --platform=linux/arm64 \
                                --driver-opt="nodeselector=kubernetes.io/arch=arm64","image=docker.io/moby/buildkit:v0.19.0"
          mkdir ~/.docker/fabric8 && cp -R ~/.docker/buildx ~/.docker/fabric8/buildx
      - name: Create settings.xml
        id: create-settings-xml
        run: |
          cat > $HOME/.m2/settings.xml << EOF
          <settings>
            <servers>
              <server>
                <id>central</id>
                <username>${{ secrets.SONATYPE_CENTRAL_REPO_TOKEN_USER }}</username>
                <password>${{ secrets.SONATYPE_CENTRAL_REPO_TOKEN_KEY }}</password>
              </server>
              <server>
                <id>ghcr.io</id>
                <username>\${env.GITHUB_ACTOR}</username>
                <password>\${env.GITHUB_TOKEN}</password>
              </server>
              <server>
                <id>pypi</id>
                <username>${{ secrets.PYPI_USERNAME }}</username>
                <password>${{ secrets.PYPI_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF
          echo "HOME_DIR=$HOME" >> "$GITHUB_OUTPUT"
      - name: Release aiSSEMBLE
        run: | 
          ./mvnw release:clean release:prepare release:perform -U -B -Pci,gh-build -DpushChanges=true -DreleaseVersion=${{ env.RELEASE_VERSION }} -DdevelopmentVersion=${{ env.NEXT_DEVELOPMENT_VERSION }} -Dgpg.keyname=aissemble@bah.com -DsignTag=true -Dmaven.build.cache.enabled=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Split version
        id: split_version_development
        uses: ./.github/actions/split_version
        with:
          version: ${{ env.NEXT_DEVELOPMENT_VERSION }}
      - name: Update Antora Docs
        uses: ./.github/actions/update_antora
        with:
          version: ${{ env.NEXT_DEVELOPMENT_VERSION }}
          patch-version: ${{ steps.split_version_development.outputs.patch-version }}
          major-minor-version: ${{ steps.split_version_development.outputs.major-minor-version }} 
          is-pre-release: ${{ steps.split_version_development.outputs.is-pre-release }}
          release-branch: ${{ steps.split_version.outputs.release-branch }}
          custom-facet-new-version: ${{ env.NEXT_DEVELOPMENT_VERSION }}
      - name: Teardown Docker builder
        id: teardown-docker-builder
        if: always()
        run: |
          docker builder rm -f $DOCKER_BUILDER_NAME

